# airflow/Dockerfile.airflow
FROM apache/airflow:3.1.3-python3.11

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        openjdk-17-jre-headless \
        curl \
        procps && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

USER airflow

COPY ../requirements.txt /requirements.txt

RUN pip install --no-cache-dir -r /requirements.txt